# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginMaitre
                                 A QGIS plugin
 Gestion des distributions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import subprocess
import os.path
import xml.etree.ElementTree as ET
from pathlib import Path

import qgis

from qgis.PyQt.QtWidgets import QDialog, QInputDialog, QLabel,QAction,QListWidgetItem,QListWidget,QMenu
from qgis.PyQt.uic import loadUi
from qgis.PyQt.QtGui import QIcon
from qgis.utils import plugins

from .maj import *
from .mapping_version import *
from .add_onglet import *
from .plugin_maitre_dialog import PluginMaitreDialog

TITRE = "Maître"
MENU_IGN = "menu IGN "
PREFIXE_PLUGIN_IGN = "IGN_"
DOSSIER_ONGLET = "config_plugin_maitre"

# 0 : bouton "actualiser/sauvegarder"
# 1 : titre des barres d'outils
# 2 : tabwidget
CUSTOM_WIDGETS = (
    "background-color: #21d847; font-weight: bold;",
    """
    QLabel {background-color: #a9ffa1;font-weight: bold;border: 2px solid #4CAF50;
        border-radius: 8px;
    }
    QLabel:hover {background-color: #70e070;color: #000000}
    """,
    """
    QTabWidget {
    background-color: #f0f0f0;}
    QTabBar::tab {background: #d0d0d0;
        padding-left : 10px;
        margin-right: 5px;
        border: 1px solid #bbb;
        }
    QTabBar::tab:selected {
        background: #37c62f;
        color: black;}
    """
)

def affiches_spec_bdtopo():
    import webbrowser
    webbrowser.open("https://bdtopoexplorer.ign.fr/")

def afficheerreur(titre,text):
    msg = QMessageBox()
    msg.setWindowTitle(titre)
    msg.setText(text)
    msg.setIcon(Warning)
    msg.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
    msg.exec()

def affichemessageAvertissement( titre, text):
    msg = QMessageBox()
    msg.setIcon(Warning)

    msg.setWindowTitle(titre)
    msg.setText(text)
    btnAnnuler = msg.addButton("Annuler", YesRole)
    btnAnnuler.setStyleSheet("color:red ; font-weight: bold")
    btnValider = msg.addButton("Supprimer", AcceptRole)
    btnValider.setStyleSheet("color:green ; font-weight: bold")
    msg.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
    msg.exec()
    if msg.clickedButton() == btnAnnuler:
        return False
    if msg.clickedButton() == btnValider:
        return True
    return None


def afficheDoc():
    fichier = Path(os.path.dirname(__file__), "plugin_maitre.pdf")
    if not os.path.isfile(fichier):
        afficheerreur("Attention", "La documentation est introuvable")
    else:
        subprocess.Popen(['start', '', fichier], shell=True)

class PluginMaitre:
    def __init__(self, iface):


        self.path_xml = None
        self.toolbar = None
        # dico de toutes les toolbars pour gérer la suppression
        self.toolbars = {}

        self.dlg = None
        self.iface = iface
        self.timer = None

        self.maj = MajPlugins()

        # Declare instance attributes
        self.actions = []

        # MENU
        self.menu = QMenu(self.iface.mainWindow())
        self.menu.setObjectName("IGN")
        self.menu.setTitle("IGN")
        self.menu_requete = None


        # list contenant les plugins IGN contenu dans le repertoire des plugins
        self.plugin_ign = []
        # liste des onglets
        self.list_onglet = []

        # list contenant les plugins cochés
        self.listplugin_coche = []

        self.getlistplugin_ign()
        self.path_xml = Path(os.path.dirname(__file__), DOSSIER_ONGLET, "tabwidget.xml")
        if not os.path.exists(self.path_xml):
            self.initXML()

        self.add_plugin_in_toolbars()
        self.init_menuIGN()



        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = True

    # creation du menu IGN
    def init_menuIGN(self):
        self.supr_plugin_to_menu()

        current_directory = os.path.dirname(__file__)
        # Remonter d'un niveau
        parent_directory = os.path.abspath(Path(current_directory, os.pardir))

        # ************************************************************************
        # plugin maitre
        icon_path = Path(os.path.dirname(__file__)) / "icons" / "icon.png"
        action = QAction(QIcon(str(icon_path)),
                         TITRE,
                         self.iface.mainWindow())
        action.triggered.connect(self.run)
        self.menu.addAction(action)
        # ************************************************************************

        # ************************************************************************
        # menu "Requêtes"
        self.menu_requete = QMenu("Requêtes", self.iface.mainWindow())
        self.menu.addMenu(self.menu_requete)
        requete = QAction("Lancer une requêtes", self.iface.mainWindow())
        requete.triggered.connect(self.on_requete)
        self.menu_requete.addAction(requete)
        # # action dans le sous-menu
        # requete_unique = QAction("Lancer une requêtes unique", self.iface.mainWindow())
        # requete_unique.triggered.connect(self.on_requete_unique)
        # requete_enchaine = QAction("Lancer une requêtes enchainées", self.iface.mainWindow())
        # requete_enchaine.triggered.connect(self.on_requete_enchaine)
        # self.menu_requete.addAction(requete_unique)
        # self.menu_requete.addAction(requete_enchaine)
        self.menu.addSeparator()

        # ************************************************************************

        # ************************************************************************
        # documentation bduni
        icon_path = Path(os.path.dirname(__file__), "icons", "spec.png")
        action = QAction(QIcon(str(icon_path)) ,"Documentation BDTopo",self.iface.mainWindow())

        action.triggered.connect(affiches_spec_bdtopo)

        self.menu.addAction(action)
        self.menu.addSeparator()
        # ************************************************************************


        # ************************************************************************
        # autre plugin
        for plugincoche in self.get_plugin_coche_fromXML(MENU_IGN):
            if plugincoche in self.plugin_ign:
                icon_path = Path(parent_directory,plugincoche,"icons","icon_principal.png")
                action = QAction(QIcon(str(icon_path)),plugincoche,self.iface.mainWindow())
                action.triggered.connect(lambda checked, plugincoche1=plugincoche: self.runplugin(plugincoche1))
                self.menu.addAction(action)
        # ************************************************************************

        # ************************************************************************
        # verif maj
        self.menu.addSeparator()
        action = QAction("Vérifiez la mise à jour des plugins", self.iface.mainWindow())
        action.triggered.connect(self.maj.on_verif_maj)
        self.menu.addAction(action)

        menuBar = self.iface.mainWindow().menuBar()
        menuBar.insertMenu(self.iface.firstRightStandardMenu().menuAction(), self.menu)

    def on_requete(self):
        self.runplugin("IGN_requetes")

    # ==================================================
    # suppression de toutes les barres d'outils
    def suppr_all_toolbar(self):
        for toolbar in self.toolbars.values():
            toolbar.setParent(None)
        self.toolbars.clear()
        self.toolbar = None

    # ==================================================
    # mise a jour des toolbars et du menu lors d'ajout de plugins
    def actualiser(self):
        list_plugin_coche = []
        # ecrire les plugins cochés dans le xml en fct des onglets
        for onglet in range(self.dlg.tabWidget.count()):
            list_plugin_coche.clear()
            nom_onglet = self.dlg.tabWidget.tabText(onglet)
            widgetlist = self.dlg.tabWidget.widget(onglet)
            for index in range(widgetlist.count()):
                if widgetlist.item(index).checkState() == Checked:
                    list_plugin_coche.append(widgetlist.item(index).text())

            # suppression de tous les plugins cochés du xml avant de réécrire
            self.suppr_all_plugincoche_toXML(nom_onglet)
            self.ecrire_plugin_coche_toXML(nom_onglet,list_plugin_coche)

        # ajout, suppression dans la toolbar
        self.add_plugin_in_toolbars()
        self.init_menuIGN()

    # ==================================================
    # "execution" du plugin en paramètre
    def runplugin(self,plugin):
        try:
            # print("Plugin demandé :", plugin)
            # print("Plugins disponibles :", list(plugins.keys()))
            processing_plugin = plugins[plugin]
            processing_plugin.initGui()  # Initialiser l'interface graphique du plugin
            processing_plugin.run()
        except KeyError:
            QMessageBox.warning(None, "Attention",
                f"le plugin {plugin} n'est pas chargé\n"
                f"Veuillez l'activer dans le menu \"Installer/Gérer les extensions de QGIS\"")



    # ==================================================
    # récupérer la liste de tous les plugins IGN installés
    def getlistplugin_ign(self):
        listplugin = qgis.utils.available_plugins
        self.plugin_ign.clear()

        for plugin in listplugin:
            if PREFIXE_PLUGIN_IGN in plugin:
                self.plugin_ign.append(plugin)
        return self.plugin_ign

    # ==================================================
    # retourne une liste avec tous les onglets du xml
    def get_onglet_fromXML(self):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        onglets = root.findall(".//onglet")
        liste_onglet = []
        for onglet in onglets:
            liste_onglet.append(onglet.get("id"))
        return liste_onglet

    # ==================================================
    # récuperation de tous les onglets du xml
    # et initialisation des onglets du tabwidget
    def init_all_onglet_fromXML(self):
        self.list_onglet.clear()
        tree  =ET.parse(self.path_xml)
        root = tree.getroot()
        onglets = root.findall(".//onglet")
        for onglet in onglets:
            listWidget = QListWidget()
            self.add_allpluginIGN_in_widgetlist(listWidget)
            self.dlg.tabWidget.addTab(listWidget,onglet.get("id"))
            # masquer la "croix" sur l'onglet menu ign
            self.dlg.tabWidget.tabBar().setTabButton(0, RightSide, None)
            self.dlg.tabWidget.tabBar().setTabButton(0, LeftSide, None)

            self.list_onglet.append(onglet.get("id"))

    # ==================================================
    # initialisation d'un listwidget avec tous les plugins "IGN" trouvés
    def add_allpluginIGN_in_widgetlist(self, listwidget):
        for plugin in self.plugin_ign:
            if PREFIXE_PLUGIN_IGN in plugin:
                itemtoolbar = QListWidgetItem()
                itemtoolbar.setFlags(ItemIsEnabled | ItemIsUserCheckable)
                itemtoolbar.setText(plugin)
                itemtoolbar.setCheckState(Unchecked)
                listwidget.addItem(itemtoolbar)

    # ==================================================
    # retourne une liste de tous les plugins du xml pour un onglet donné
    def get_plugin_coche_fromXML(self,onglet):
        # charge le xml existant
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        onglet_xml = root.find(f".//onglet[@id='{onglet}']")
        list_coche = []
        if onglet_xml is not None:
            for plugin in onglet_xml.findall("plugin"):
                list_coche.append(plugin.text)
        return list_coche

    # ==================================================
    # pour chaque onglet on "coche" ou pas chaque plugin dans le tabwidget
    def initialiselistwidgetcoche(self):
        # la recuperation se fait à partir du tabwidget et non du xml (à voir).
        list_coche = []
        for index in range(self.dlg.tabWidget.count()):
            list_coche.clear()
            widgetlist = self.dlg.tabWidget.widget(index)
            nom = self.dlg.tabWidget.tabText(index)
            list_coche = self.get_plugin_coche_fromXML(nom)

            # pour chaque widgetlist, on coche
            for plugin_coche in list_coche:
                item_find = widgetlist.findItems(plugin_coche, MatchExactly)
                if len(item_find) != 0:
                    item_find[0].setText(plugin_coche)
                    item_find[0].setSelected(True)
                    item_find[0].setCheckState(Checked)

    # ==================================================
    # si xml absent : creation d'un xml par défaut avec un plugin par défaut
    def initXML(self):
        # Créer le dossier s'il n'existe pas
        os.makedirs(Path(os.path.dirname(__file__), DOSSIER_ONGLET), exist_ok=True)
        # Racine uniquement
        root = ET.Element("tabwidget")
        ET.SubElement(root, "onglet", id=MENU_IGN)
        # Écriture dans le fichier
        tree = ET.ElementTree(root)
        tree.write(self.path_xml, encoding="utf-8", xml_declaration=True)


    # ==================================================
    # écriture du xml avec tous les plugins cochés en fonction de l'onglet
    def ecrire_plugin_coche_toXML(self,onglet,list_plugin_coche):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        ongletXml = root.find(f".//onglet[@id='{onglet}']")
        for plugin in list_plugin_coche:
            pluginXml = ET.SubElement(ongletXml,"plugin")
            pluginXml.text = plugin
        ET.indent(root, "    ")
        tree.write(self.path_xml,encoding='utf-8', xml_declaration=True)

    # ==================================================
    # suppression de tous les plugins du xml
    def suppr_all_plugincoche_toXML(self,onglet):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        onglet_xml = root.find(f".//onglet[@id='{onglet}']")
        if onglet_xml is not None:
            for plugin in onglet_xml.findall("plugin"):
                onglet_xml.remove(plugin)
            tree.write(self.path_xml,encoding='utf-8', xml_declaration=True)

    # ==================================================
    # suppression d'un onglet (xml,barre d'outils et tabwidget)
    def supp_onglet(self, index: int):
        nom_onglet = self.dlg.tabWidget.tabText(index)
        if affichemessageAvertissement("Avertissement", "Voulez vous vraiment supprimer cette barre d'outils ?"):
            # suppression de l'onglet dans le xml
            self.suppr_ongletXML(index)
            # suppression de l'onglet dans le tabwidget
            self.dlg.tabWidget.removeTab(index)
            # suppression de la barre d'outils
            if hasattr(self, "toolbars") and nom_onglet in self.toolbars:
                self.toolbars[nom_onglet].setParent(None)
                del self.toolbars[nom_onglet]

    # ==================================================
    # suppression de tous les plugins du menu ign
    def supr_plugin_to_menu(self):
        action_to_remove = self.menu.actions()
        for action in action_to_remove:
            self.menu.removeAction(action)

    # ==================================================
    # ajout les plugins aux différentes toolbar en fct du xml
    def add_plugin_in_toolbars(self):
        self.suppr_all_toolbar()
        current_directory = os.path.dirname(__file__)
        # Remonter d'un niveau
        parent_directory = os.path.abspath(Path(current_directory, os.pardir))
        # récupérer les onglets du xml ici et boucler
        for onglet in self.get_onglet_fromXML():
            if onglet != MENU_IGN:
                # si l'onglet n'a pas de plugin défini, on n'ajoute pas à la barre d'outil,
                # mais il reste dans le xml si on veut ajouter des plugins par la suite
                if len(self.get_plugin_coche_fromXML(onglet)) == 0:
                    return

                self.toolbar = self.iface.addToolBar(onglet)
                self.toolbars[onglet] = self.toolbar
                if onglet != MENU_IGN:
                    # libellé devant chaque barre d'outils
                    label_toolbar = QLabel(onglet)
                    label_toolbar.setStyleSheet(CUSTOM_WIDGETS[1])
                    self.toolbar.addWidget(label_toolbar)

                    for plugincoche in self.get_plugin_coche_fromXML(onglet):
                        icon_path = Path(parent_directory, plugincoche, "icons", "icon_principal.png")
                        action = QAction(QIcon(str(icon_path)), plugincoche, self.iface.mainWindow())
                        action.triggered.connect(
                            lambda checked, plugincoche1=plugincoche: self.runplugin(plugincoche1))
                        # ajout d'un attribut pour utiliser plusieurs instances différentes de self.toolbar
                        setattr(self, onglet, self.toolbar)
                        self.toolbar.addAction(action)

    # ==================================================
    # ajout d'un onglet dans le xml et dans le tabwidget
    def add_onglet(self):
        nom_barre = self.dlgaddonglet.lineEdit_newonglet.text()
        if nom_barre == "":
            return
        for i in range(self.dlg.tabWidget.count()):
            if self.dlg.tabWidget.tabText(i) == nom_barre:
                afficheerreur("Avertissement","Ce nom existe déjà !")
                self.dlgaddonglet.lineEdit_newonglet.clear()
                return
        nb_onglet = self.dlg.tabWidget.count()

        listWidget = QListWidget()
        self.add_allpluginIGN_in_widgetlist(listWidget)
        self.dlg.tabWidget.addTab(listWidget, nom_barre)

        self.dlg.tabWidget.setCurrentIndex(nb_onglet)

        # ecriture du fichier de config correspondant à l'onglet ajouté
        self.add_ongletXML(nom_barre)
        self.dlgaddonglet.hide()

    # ==================================================
    # ouverture du dialogue d'ajout d'un onglet
    def show_dial_add_onglet(self):
        self.dlgaddonglet.lineEdit_newonglet.clear()
        self.dlgaddonglet.lineEdit_newonglet.setFocus()
        # self.dlgaddinglet.show()
        self.dlgaddonglet.exec()

    # ==================================================
    # ouverture du dialogue "à propos de"
    def apropos(self):
        dlgAProposDe = QDialog()
        loadUi(os.path.dirname(__file__) + "/aproposde.ui", dlgAProposDe)
        dlgAProposDe.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        dlgAProposDe.setWindowTitle(f"{TITRE}")
        dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)
        dlgAProposDe.exec()

    # ==================================================
    # renommer un onglet dans le xml
    # et actualisation de l'interface
    def renomme_onglet(self):
        index = self.dlg.tabWidget.currentIndex()
        if index == 0:
            afficheerreur("Avertissement","Impossible de renommer le menu IGN")
            return
        ancien_nom = self.dlg.tabWidget.tabText(index)
        nouveau_nom,ok =QInputDialog.getText(None,"Renommer la barre d'outils","Nouveau nom :",text = ancien_nom)
        # ... et different du menu IGN
        if ok and nouveau_nom and index != 0:
            self.dlg.tabWidget.setTabText(index, nouveau_nom)
            tree = ET.parse(self.path_xml)
            root = tree.getroot()
            ongletXml = root.find(f".//onglet[@id='{ancien_nom}']")
            if ongletXml is None:
                return
            # Modifier l’attribut id
            ongletXml.set("id", nouveau_nom)
            ET.indent(tree, "    ")
            tree.write(self.path_xml, encoding="utf-8", xml_declaration=True)

            self.actualiser()

    # ==================================================
    # suppression d'un onglet dans le xml
    def suppr_ongletXML(self,index):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        for onglet in root.findall(".//onglet"):
            if onglet.get("id") == self.dlg.tabWidget.tabText(index):
                root.remove(onglet)
        tree.write(self.path_xml, encoding='utf-8', xml_declaration=True)

    # ==================================================
    # ajout onglet et plugins cochés dans le xml
    def add_ongletXML(self,nom):
        # charge le xml existant
        tree = ET.parse(self.path_xml)
        root = tree.getroot()

        # creation nouvel onglet
        new_onglet = ET.Element("onglet",id = nom)
        root.append(new_onglet)

        # mise en page : indentation
        ET.indent(root, "    ")
        tree.write(self.path_xml, encoding='utf-8', xml_declaration=True)

    def initGui(self):
        QTimer.singleShot(200, self.maj.download_plugins_xml)
        self.first_start = True

    def unload(self):
        self.suppr_all_toolbar()
        self.menu.deleteLater()

    # ==================================================
    def run(self):
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = PluginMaitreDialog()
            self.dlg.setWindowTitle(f"{TITRE}")
            self.dlg.setParent(self.iface.mainWindow())
            self.dlg.setWindowFlags(Dialog | WindowTitleHint | WindowCloseButtonHint)


            # dial d'ajout d'onglet
            self.dlgaddonglet = AddOnglet()
            self.dlgaddonglet.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
            self.dlgaddonglet.pushButton_addonglet.clicked.connect(self.add_onglet)

            # a propos...
            self.dlg.pushButton_apropos.clicked.connect(self.apropos)

            # bouton actualiser la toolbar
            self.dlg.pushButtonActualiser.clicked.connect(self.actualiser)
            self.dlg.pushButtonActualiser.setStyleSheet(CUSTOM_WIDGETS[0])
            # ajouter une toolbar
            self.dlg.pushButtonAddBarre.clicked.connect(self.show_dial_add_onglet)
            # bouton renommer
            self.dlg.pushButton_renommer.clicked.connect(self.renomme_onglet)
            # Connecter le signal 'tabRemoved' à un slot
            self.dlg.tabWidget.tabCloseRequested.connect(self.supp_onglet)

            # suppression
            self.supr_plugin_to_menu()
            # suppression des plugins de la toolbar avant de la réinitialiser
            # self.supr_plugin_to_toolbar()

            # suppr des onglets
            self.dlg.tabWidget.clear()

            # apparence du tabwidget
            self.dlg.tabWidget.setStyleSheet(CUSTOM_WIDGETS[2])

            # recuperation de tous les onglets du xml
            # initialisation des onglets du tabwidget
            self.init_all_onglet_fromXML()

            # initialisation des listwidget pour chaque onglet du xml (coché)
            self.initialiselistwidgetcoche()

            self.add_plugin_in_toolbars()
            self.init_menuIGN()

            self.dlg.exec()

            self.first_start = True

